spring:
  profiles:
    active: local
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 60000
      connect-timeout: 60000
  datasource:
    url: "jdbc:mysql://localhost:3306/fast"
    username: root
    password: 1234

    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      connection-timeout: 30000   # (optional) 30초 대기 후 실패
#logging:
#  level:
#    root: debug

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

---

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql:  true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
jwt:
  secret: dsadsadsamnzxvzclklewqioewqo!!#@#$@$@$@$@)$(@%(@(%(


---

spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  sql:
    init:
      mode: never
